package uk.ac.kent.computing.gttm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.io.*;
import java.text.*;
import java.util.*;
import uk.ac.kent.computing.gttm.GrammarIllustrator.GrammarIllustrator;

import uk.ac.kent.computing.gttm.GrammarIllustrator.GrammarIllustrator;
import uk.ac.kent.computing.gttm.Grammar_Elements.GrammarContainer;


/**
 *
 * @author Alexander
 */
public class GrammarDrawer extends javax.swing.JFrame {

    /**
     * Creates new form GrammarDrawer
     */
    public GrammarDrawer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        grammarIllustrator1 = new GrammarIllustrator();
        jScrollPane5 = new javax.swing.JScrollPane();
        grammarIllustrator2 = new GrammarIllustrator();
        try {
            FileInputStream fileIn = new FileInputStream("Grammars/grammar-2015-08-02-01-26-40.ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            GrammarContainer grammar = (GrammarContainer) in.readObject();
            in.close();
            fileIn.close();

            grammarIllustrator2.setNewGrammar(grammar);

        } catch (IOException i) {
            i.printStackTrace();
            return;
        } catch (ClassNotFoundException c) {

        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout grammarIllustrator2Layout = new javax.swing.GroupLayout(grammarIllustrator2);
        grammarIllustrator2.setLayout(grammarIllustrator2Layout);
        grammarIllustrator2Layout.setHorizontalGroup(
            grammarIllustrator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        grammarIllustrator2Layout.setVerticalGroup(
            grammarIllustrator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(grammarIllustrator2);

        javax.swing.GroupLayout grammarIllustrator1Layout = new javax.swing.GroupLayout(grammarIllustrator1);
        grammarIllustrator1.setLayout(grammarIllustrator1Layout);
        grammarIllustrator1Layout.setHorizontalGroup(
            grammarIllustrator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grammarIllustrator1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        grammarIllustrator1Layout.setVerticalGroup(
            grammarIllustrator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grammarIllustrator1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(grammarIllustrator1);

        getContentPane().add(jScrollPane4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrammarDrawer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrammarDrawer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrammarDrawer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrammarDrawer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrammarDrawer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GrammarIllustrator grammarIllustrator1;
    private GrammarIllustrator grammarIllustrator2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
